spring:
  config:
    activate:
      on-profile: pre-proc
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
    inetutils:
      default-hostname: yamp-backend.ngodat0103.live
  data:
    redis:
      url: redis://redis-svc:6379
      client-type: lettuce
      database: 1
      client-name: gateway-svc
  security:
    oauth2:
      client:
        provider:
          auth-service:
            authorization-uri: http://${spring.cloud.inetutils.default-hostname}:8000/api/v1/auth/oauth2/authorize
            token-uri: http://${spring.cloud.inetutils.default-hostname}:8000/api/v1/auth/oauth2/token
            jwk-set-uri: http://auth-svc:8001/api/v1/auth/oauth2/jwks
        registration:
#          swagger-client:
#            redirect-uri: "http://${spring.cloud.inetutils.default-hostname}:8000/login/oauth2/code/swagger-client"
#            provider: auth-service
#            authorization-grant-type: authorization_code
#            client-authentication-method: client_secret_basic
#            client-id: swagger-client
#            client-secret: "{cipher}dcbe3d737b10508e19c95bf72cfe2d22b734104965350a20d6297ebed9953bdfabd761772530e5bb6c2fbc7e30d64551"
          gateway-service:
            redirect-uri: "http://${spring.cloud.inetutils.default-hostname}:8000/login/oauth2/code/gateway-service"
            provider: auth-service
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            client-id: gateway-service
            client-secret: "{cipher}806472b06e24fc5a178e34594f1c6406cc662fb95c63596dece4d03e10bd8ee6ba014c5d22f5b13ce206544f3cbb2e20"
            scope: user.read,openid,profile,message.read,message.write
      resourceserver:
        jwt:
          authorities-claim-name: "roles"
          authority-prefix: "ROLE_"
          jwk-set-uri: http://auth-svc:8001/api/v1/auth/oauth2/jwks


logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
  level:
    com.github.ngodat0103.yamp.gateway: DEBUG
    org.springframework.security: DEBUG


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /ui-docs
    enabled: true
    oauth:
      client-id: swagger-client
      client-secret: "{cipher}dcbe3d737b10508e19c95bf72cfe2d22b734104965350a20d6297ebed9953bdfabd761772530e5bb6c2fbc7e30d64551"
      use-basic-authentication-with-access-code-grant: true
    oauth2-redirect-url: http://${spring.cloud.inetutils.default-hostname}:8000/webjars/swagger-ui/oauth2-redirect.html
    urls:
      - name: "auth-svc"
        url: "http://${spring.cloud.inetutils.default-hostname}:8000/api/v1/auth/api-docs"
      - name: "user-svc"
        url: "http://${spring.cloud.inetutils.default-hostname}:8000/api/v1/user/api-docs"
    use-root-path: true
