apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPAuth
metadata:
  name: hcpauth
spec:
  organizationID: cbe1cf74-4825-4a1b-8c63-c685c98f813c
  projectID: d0064e9e-e611-4d22-8151-d54a515c513d
  servicePrincipal:
    secretRef: hcp-k8s-operator-principal-secret
