apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-svc-deployment
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: user-svc
  template:
    metadata:
      labels:
        app: user-svc
    spec:
      imagePullSecrets:
        - name: {{.Values.imagePullSecrets.name}}
      containers:
        - name: user-svc
          image: {{.Values.yamp.usersvc.repo}}:{{.Chart.AppVersion}}
          envFrom:
            - configMapRef:
                name: {{.Values.configmap.tempo}}
            - secretRef:
                name: user-svc-secret
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{.Values.spring.profiles.active}}
          imagePullPolicy: Always
          ports:
            - containerPort: 8002
          resources:
            requests:
              memory: {{.Values.resources.requests.memory}}
              cpu: {{.Values.resources.requests.cpu}}
            limits:
              memory: {{.Values.resources.limits.memory}}
              cpu: {{.Values.resources.limits.cpu}}
          livenessProbe:
            httpGet:
              path: /api/v1/user/actuator/health/liveness
              port: 8002
            initialDelaySeconds: {{.Values.probes.initialDelaySeconds}}
            periodSeconds: {{.Values.probes.periodSeconds}}
            timeoutSeconds: {{.Values.probes.timeoutSeconds}}
            failureThreshold: {{.Values.probes.failureThreshold}}
          readinessProbe:
            httpGet:
              port: 8002
              path: /api/v1/user/actuator/health/readiness
            initialDelaySeconds: {{.Values.probes.initialDelaySeconds}}
            periodSeconds: {{.Values.probes.periodSeconds}}
            timeoutSeconds: {{.Values.probes.timeoutSeconds}}
            failureThreshold: {{.Values.probes.failureThreshold}}