apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-svc-configmap
data:
  pre-proc.yaml: |
    spring:
      config:
        activate:
          on-profile: pre-proc
      cloud:
        inetutils:
          default-hostname: yamp-backend.ngodat0103.live
    springdoc:
      api-docs:
        path: /api-docs
      swagger-ui:
        path: /ui-docs
        enabled: true
        oauth:
          use-basic-authentication-with-access-code-grant: true
        oauth2-redirect-url: https://${spring.cloud.inetutils.default-hostname}/webjars/swagger-ui/oauth2-redirect.html
        urls:
          - name: "auth-svc"
            url: "https://${spring.cloud.inetutils.default-hostname}/api/v1/auth/api-docs"
          - name: "user-svc"
            url: "https://${spring.cloud.inetutils.default-hostname}/api/v1/user/api-docs"
        use-root-path: true