apiVersion: v1
kind: ConfigMap
metadata:
  name: user-svc-configmap
data:
  pre-proc.yaml: |
    spring:
      config:
        activate:
          on-profile: pre-proc
      cloud:
        inetutils:
          default-hostname: yamp-backend.ngodat0103.live
      datasource:
        url: jdbc:postgresql://share-db:5432/user-svc-db
        driver-class-name: org.postgresql.Driver
      jpa:
        hibernate:
          ddl-auto: update
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
      security:
        oauth2:
          client:
            provider:
              auth-service-external:
                authorization-uri: https://${spring.cloud.inetutils.default-hostname}/api/v1/auth/oauth2/authorize
                token-uri: https://${spring.cloud.inetutils.default-hostname}/api/v1/auth/oauth2/token
                jwk-set-uri: https://${spring.cloud.inetutils.default-hostname}/api/v1/auth/oauth2/jwks
    management:
      endpoints:
        web:
          exposure:
            include: "*"
      health:
        readiness-state:
          enabled: true
        liveness-state:
          enabled: true
      info:
        env:
          enabled: true
      metrics:
        tags:
          application: ${spring.application.name}
      endpoint:
        health:
          show-details: always
