apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-common-configmap
data:
  JAVA_TOOL_OPTIONS: '{{.Values.tempo.agentClassPath}}'
  OTEL_METRICS_EXPORTER: "none"
  OTEL_EXPORTER_OTLP_ENDPOINT: "{{.Values.tempo.URL}}"