apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPVaultSecretsApp
metadata:
  name: auth-svc-hcpvaultsecretapp
spec:
  appName: auth-svc
  destination:
    create: true
    name: auth-svc-secret
  hcpAuthRef: hcpauth
  refreshAfter: 1h