apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPVaultSecretsApp
metadata:
  name: user-svc-hcpvaultsecretsapp
spec:
  appName: user-svc
  destination:
    create: true
    name: user-svc-secret
  hcpAuthRef: hcpauth
  refreshAfter: 1h