apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-user-svc
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-svc-deployment
  minReplicas: {{.Values.autoscaling.minReplicas}}
  maxReplicas: {{.Values.autoscaling.maxReplicas}}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{.Values.autoscaling.targetCPUUtilizationPercentage}}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{.Values.autoscaling.targetMemoryUtilizationPercentage}}
