apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPVaultSecretsApp
metadata:
  name: gateway-svc-hcpvaultsecretsapp
spec:
  appName: gateway-svc
  destination:
    create: true
    name: gateway-svc-secret
  hcpAuthRef: hcpauth
  refreshAfter: 1h