apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-svc-deployment
spec:
  replicas: {{.Values.replicaCount}}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: auth-svc
  template:
    metadata:
      labels:
        app: auth-svc
    spec:
      imagePullSecrets:
        - name: {{.Values.imagePullSecrets.name}}
      containers:
        - name: auth-svc
          image: {{.Values.yamp.authsvc.repo}}:{{.Chart.AppVersion}}
          envFrom:
            - configMapRef:
                name: {{.Values.configmap.tempo}}
            - secretRef:
                name: auth-svc-secret
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: {{.Values.kafka.producerURL}}
            - name: SPRING_PROFILES_ACTIVE
              value: {{.Values.spring.profiles.active}}
            - name: APP_VERSION
              value: {{.Chart.AppVersion}}
            - name: SPRING_DATASOURCE_URL
              value: {{.Values.yamp.authsvc.datasourceUrl}}
            - name: SPRING_DATA_REDIS_URL
              value: {{.Values.redis.url}}

          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          resources:
            requests:
              memory: {{.Values.resources.requests.memory}}
              cpu: {{.Values.resources.requests.cpu}}
            limits:
              memory: {{.Values.resources.limits.memory}}
              cpu: {{.Values.resources.limits.cpu}}
          livenessProbe:
            httpGet:
              path: /api/v1/auth/actuator/health/liveness
              port: 8001
            initialDelaySeconds: {{.Values.probes.liveness.initialDelaySeconds}}
            periodSeconds: {{.Values.probes.periodSeconds}}
            timeoutSeconds: {{.Values.probes.timeoutSeconds}}
            failureThreshold: {{.Values.probes.failureThreshold}}
          readinessProbe:
            httpGet:
              port: 8001
              path: /api/v1/auth/actuator/health/readiness
            initialDelaySeconds: {{.Values.probes.readiness.initialDelaySeconds}}
            periodSeconds: {{.Values.probes.periodSeconds}}
            timeoutSeconds: {{.Values.probes.timeoutSeconds}}
            failureThreshold: {{.Values.probes.failureThreshold}}



