apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPVaultSecretsApp
metadata:
  name: share-db-hcpvaultsecretsapp
spec:
  appName: share-db
  destination:
    create: true
    name: share-db-secret
  hcpAuthRef: hcpauth
  refreshAfter: 1h