apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-svc
  template:
    metadata:
      labels:
        app: user-svc
    spec:
      volumes:
        - name: prep-proc-profile
          configMap:
            name: user-svc-configmap
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: auth-svc
          image: ghcr.io/ngodat0103/yamp/user-svc:0.0.1-pre.80f81b2
          imagePullPolicy: Always
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          volumeMounts:
            - mountPath: /opt/app/BOOT-INF/classes/pre-proc.yaml
              name: prep-proc-profile
              subPath: pre-proc.yaml
          envFrom:
            - secretRef:
                name: user-svc-secret
            - configMapRef:
                name: tempo-common-configmap
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: pre-proc
          ports:
            - containerPort: 8002