apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-svc-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-svc
  template:
    metadata:
      labels:
        app: auth-svc
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: auth-svc
          image: ghcr.io/ngodat0103/yamp/auth-svc:pr-latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: pre-proc
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: auth-svc-secret
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-svc-secret
                  key: SPRING_DATASOURCE_PASSWORD
            - name: K8S_SECRET_JWK
              valueFrom:
                secretKeyRef:
                  name: auth-svc-secret
                  key: K8S_SECRET_JWK
          imagePullPolicy: Always
          ports:
            - containerPort: 8001