prometheus:
  prometheusSpec:
    additionalScrapeConfigs: |
      - job_name: "auth-svc"
        metrics_path: '/api/v1/auth/actuator/prometheus'
        static_configs:
          - targets: ['auth-svc.yamp.svc.cluster.local:8001']
      - job_name: 'user-svc'
        metrics_path: '/api/v1/user/actuator/prometheus'
        static_configs:
          - targets: ['user-svc.yamp.svc.cluster.local:8002']
      - job_name: 'product-svc'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['product-svc.yamp.svc.cluster.local:8003']