apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-svc-deployment
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: product-svc
  template:
    metadata:
      labels:
        app: product-svc
    spec:
      imagePullSecrets:
        - name: {{.Values.imagePullSecrets.name}}
      containers:
        - name: product-svc
          image: {{.Values.yamp.productsvc.repo}}:{{.Values.yamp.productsvc.version}}
          envFrom:
            - configMapRef:
                name: {{.Values.configmap.tempo}}
            - secretRef:
                name: product-svc-secret
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{.Values.spring.profiles.active}}
            - name: APP_VERSION
              value: {{.Chart.AppVersion}}
            - name: SPRING_DATASOURCE_URL
              value: {{.Values.yamp.productsvc.datasourceUrl}}
          imagePullPolicy: Always
          ports:
            - containerPort: 8003
          resources:
            requests:
              memory: {{.Values.resources.requests.memory}}
              cpu: {{.Values.resources.requests.cpu}}
            limits:
              memory: {{.Values.resources.limits.memory}}
              cpu: {{.Values.resources.limits.cpu}}
          livenessProbe:
            httpGet:
              path: /api/v1/product/actuator/health/liveness
              port: 8003
            initialDelaySeconds: {{.Values.probes.liveness.initialDelaySeconds}}
            periodSeconds: {{.Values.probes.periodSeconds}}
            timeoutSeconds: {{.Values.probes.timeoutSeconds}}
            failureThreshold: {{.Values.probes.failureThreshold}}
          readinessProbe:
            httpGet:
              port: 8003
              path: /api/v1/product/actuator/health/readiness
            initialDelaySeconds: {{.Values.probes.readiness.initialDelaySeconds}}
            periodSeconds: {{.Values.probes.periodSeconds}}
            timeoutSeconds: {{.Values.probes.timeoutSeconds}}
            failureThreshold: {{.Values.probes.failureThreshold}}