apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-svc
  template:
    metadata:
      labels:
        app: user-svc
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: auth-svc
          image: ghcr.io/ngodat0103/yamp/user-svc:pr-latest
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: pre-proc
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: user-svc-secret
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-svc-secret
                  key: SPRING_DATASOURCE_PASSWORD
          ports:
            - containerPort: 8002