apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway-svc
  template:
    metadata:
      labels:
        app: gateway-svc
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: gateway-svc
          image: ghcr.io/ngodat0103/yamp/gateway-svc:pr-latest
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: pre-proc
            - name: SPRINGDOC_SWAGGER_UI_OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: gateway-svc-secret
                  key: SPRINGDOC_SWAGGER_UI_OAUTH_CLIENT_ID
            - name: SPRINGDOC_SWAGGER_UI_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: gateway-svc-secret
                  key: SPRINGDOC_SWAGGER_UI_OAUTH_CLIENT_SECRET
            - name: ENCRYPT_KEY
              valueFrom:
                secretKeyRef:
                  name: gateway-svc-secret
                  key: ENCRYPT_KEY
          ports:
            - containerPort: 8000