apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPVaultSecretsApp
metadata:
  name: redis-hcpvaultsecretsapp
spec:
  appName: redis
  destination:
    create: true
    name: redis-secret
  hcpAuthRef: hcpauth
  refreshAfter: 1h