Vagrant.configure("2") do |config|
  # Define the base box
  config.vm.box = "ubuntu/jammy64"

  # Define the first VM (master)
  config.vm.define "master" do |master|
    master.vm.hostname = "master"
    master.vm.network "public_network"
    config.vm.network "private_network", ip: "192.168.8.10"
    master.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = 2
    end
  end

  # Define the second VM (worker1)
  config.vm.define "worker1" do |worker1|
    worker1.vm.hostname = "worker1"
    worker1.vm.network "public_network"
        config.vm.network "private_network", ip: "192.168.8.11"
    worker1.vm.provider "virtualbox" do |vb|
      vb.memory = "8192"
      vb.cpus = 4
    end
  end

  # Define the third VM (worker2)
  config.vm.define "worker2" do |worker2|
    worker2.vm.hostname = "worker2"
    worker2.vm.network "public_network"
    config.vm.network "private_network", ip: "192.168.8.12"
    worker2.vm.provider "virtualbox" do |vb|
      vb.memory = "8192"
      vb.cpus = 4
    end
  end
end