---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: share-db-pvc
spec:
    accessModes:
        - ReadWriteOnce
        - ReadOnlyMany
    resources:
        requests:
            storage: 1Gi
        limits:
            storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: share-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: share-db
  template:
    metadata:
      labels:
        app: share-db
    spec:
      volumes:
        - name: pvc
          persistentVolumeClaim:
            claimName: share-db-pvc
        - name: init-sql
          secret:
            secretName: share-db-secret
            items:
              - key: INIT_SQL
                path: init.sql
      containers:
        - image:  postgres:16.3-bullseye
          name: share-db
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: share-db-secret
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/
              name: init-sql
            - name: pvc
              mountPath: /var/lib/postgresql/data

---
apiVersion: v1
kind: Service
metadata:
  name: share-db
spec:
    selector:
        app: share-db
    ports:
      - protocol: TCP
        port: 5432
        targetPort: 5432
    type: ClusterIP


