prometheus:
  prometheusSpec:
    scrapeInterval: 5s
    additionalScrapeConfigs:
      - job_name: "auth-svc"
        metrics_path: '/api/v1/auth/actuator/prometheus'
        static_configs:
          - targets: [ 'auth-svc.prod-yamp.svc.cluster.local:8001' ]
      - job_name: 'user-svc'
        metrics_path: '/api/v1/user/actuator/prometheus'
        static_configs:
          - targets: [ 'user-svc.prod-yamp.svc.cluster.local:8002' ]
      - job_name: 'gateway-svc'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'gateway-svc.prod-yamp.svc.cluster.local:8000' ]
      - job_name: 'product-svc'
        metrics_path: '/api/v1/product/actuator/prometheus'
        static_configs:
          - targets: [ 'product-svc.default.svc.cluster.local:8003' ]
grafana:
  additionalDataSources:
    - name: Tempo
      type: tempo
      uid: tempo
      url: http://tempo-release.monitoring.svc.cluster.local:3100
      access: proxy
      orgId: 1
      basicAuth: false
      isDefault: false
      version: 1
      editable: true
      jsonData:
        httpMethod: GET
        serviceMap:
          datasourceUid: 'prometheus'
    - name: Loki
      type: loki
      uid: loki
      access: proxy
      orgId: 1
      editable: true
      url: http://loki.monitoring.svc.cluster.local:3100
      jsonData:
        httpHeaderName1: "X-Scope-OrgID"
        derivedFields:
          - datasourceUid: tempo
            matcherRegex: "\\[.+,(.+),.+\\]"
            name: TraceID
            url: '$${__value.raw}'
      secureJsonData:
        httpHeaderValue1: "tenant1"