apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yamp-application-staging
  namespace: argocd
spec:
  project: default
  source:
    chart: yamp
    repoURL: https://charts.ngodat0103.live/yamp
    targetRevision: 0.0.1
  destination:
    server: https://kubernetes.default.svc
    namespace: prod-yamp
  syncPolicy:
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
